In [1]:
import sqlite3 

import pandas as pd

#create connection with new database 
conn = sqlite3.connect ("ecommerce.db")


#read kaggle file 
df = pd.read_csv('C:/Users/PLUS VAIO/OneDrive/سطح المكتب/projects/ecommerce/data.csv', encoding = 'latin1')


df.to_sql("ecommerce", conn, if_exists = 'replace', index = False)

541909

In [2]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [3]:
#المنتج الأكثر مبيعاً
#top 5 selling products
pd.read_sql_query("""
SELECT Description, SUM(Quantity) AS total_sold from ecommerce GROUP BY Description ORDER BY total_sold DESC LIMIT 5;
""",conn)

                         Description  total_sold
0  WORLD WAR 2 GLIDERS ASSTD DESIGNS       53847
1            JUMBO BAG RED RETROSPOT       47363
2      ASSORTED COLOUR BIRD ORNAMENT       36381
3                     POPCORN HOLDER       36334
4    PACK OF 72 RETROSPOT CAKE CASES       36039

In [4]:
#الزبائن الأكثر شراء 
#Most Expenditure Clients
pd.read_sql_query("""SELECT CustomerID,  SUM(Quantity * UnitPrice) AS total_spent FROM ecommerce GROUP BY CustomerID ORDER BY total_spent DESC LIMIT 10;""",conn )

   CustomerID  total_spent
0         NaN   1447682.12
1     14646.0    279489.02
2     18102.0    256438.49
3     17450.0    187482.17
4     14911.0    132572.62
5     12415.0    123725.45
6     14156.0    113384.14
7     17511.0     88125.38
8     16684.0     65892.08
9     13694.0     62653.10

In [5]:
#الفواتير الأغلى
#Hieghest Invoices
pd.read_sql_query("""SELECT InvoiceNo, SUM(Quantity * UnitPrice) AS total_spent FROM ecommerce GROUP BY InvoiceNo ORDER BY total_spent DESC LIMIT 10;""",conn )

  InvoiceNo  total_spent
0    581483    168469.60
1    541431     77183.60
2    574941     52940.94
3    576365     50653.91
4    556444     38970.00
5    567423     31698.16
6    556917     22775.93
7    572209     22206.00
8    567381     22104.80
9    563614     21880.44

In [6]:
#البلدان الأكثر مبيعا للمنتجات
#top quantity per country  
pd.read_sql_query("""SELECT Country,SUM(Quantity) AS total_quantity FROM ecommerce GROUP BY Country ORDER BY total_quantity DESC LIMIT 5""",conn)

          Country  total_quantity
0  United Kingdom         4263829
1     Netherlands          200128
2            EIRE          142637
3         Germany          117448
4          France          110480

In [7]:
#الدولة ذات عدد الفواتير الأعلى
#Invoice number per country
pd.read_sql_query("""SELECT Country,COUNT(InvoiceNo) AS invoice_number FROM ecommerce GROUP BY Country ORDER BY invoice_number DESC LIMIT 5""",conn)

          Country  invoice_number
0  United Kingdom          495478
1         Germany            9495
2          France            8557
3            EIRE            8196
4           Spain            2533

In [8]:
#عدد الزبائن الكلي 
#number of distinct customers
pd.read_sql_query("""SELECT COUNT(DISTINCT CustomerID) AS unique_customers FROM ecommerce WHERE CustomerID IS NOT NULL""",conn)

   unique_customers
0              4372

In [93]:
#عدد البلاد في العينة المدروسة 
#number of distinct country
pd.read_sql_query("""SELECT COUNT(DISTINCT Country) AS unique_country FROM ecommerce """,conn)

   unique_country
0              38

In [70]:
#عدد الفواتير في العينة المدروسة 
#number of distinct customers
pd.read_sql_query("""SELECT COUNT(DISTINCT InvoiceNo) AS unique_invoice FROM ecommerce WHERE InvoiceNo IS NOT NULL""",conn)

   unique_invoice
0           25900

In [80]:
#عدد عمليات البيع(الفواتير) لكل زبون
pd.read_sql_query("""SELECT Country,CustomerID, COUNT(DISTINCT InvoiceNo) AS invoice_per_customer FROM ecommerce WHERE CustomerID IS NOT NULL GROUP BY CustomerID ORDER BY invoice_per_customer DESC LIMIT 5 """,conn)

          Country  CustomerID  invoice_per_customer
0            EIRE     14911.0                   248
1  United Kingdom     12748.0                   224
2  United Kingdom     17841.0                   169
3  United Kingdom     14606.0                   128
4  United Kingdom     15311.0                   118

In [10]:
df["CustomerID"].nunique()

4372

In [81]:
#البلدان الأكثر كميات مبيعا
pd.read_sql_query("""SELECT Country, SUM(Quantity) AS quantity_per_country FROM ecommerce WHERE Country IS NOT NULL GROUP BY Country ORDER BY quantity_per_country DESC LIMIT 5 """,conn)

          Country  quantity_per_country
0  United Kingdom               4263829
1     Netherlands                200128
2            EIRE                142637
3         Germany                117448
4          France                110480

In [11]:
#top 10 countries by average pruduct price
pd.read_sql_query("""SELECT Country,avg(UnitPrice) AS avg_pruduct_price FROM ecommerce GROUP BY Country ORDER BY avg_pruduct_price DESC LIMIT 10""",conn)

     Country  avg_pruduct_price
0  Singapore         109.645808
1  Hong Kong          42.505208
2   Portugal           8.582976
3     Cyprus           6.302363
4     Canada           6.030331
5     Norway           6.012026
6       EIRE           5.911077
7    Finland           5.448705
8    Lebanon           5.387556
9      Malta           5.244173

In [12]:
#lowest 10 countries by average pruduct price

pd.read_sql_query("""SELECT Country,avg(UnitPrice) AS avg_pruduct_price FROM ecommerce GROUP BY Country ORDER BY avg_pruduct_price ASC LIMIT 10""",conn)

          Country  avg_pruduct_price
0             USA           2.216426
1           Japan           2.276145
2    Saudi Arabia           2.411000
3         Iceland           2.644011
4     Unspecified           2.699574
5     Netherlands           2.738317
6       Lithuania           2.841143
7  Czech Republic           2.938333
8       Australia           3.220612
9         Denmark           3.256941

In [13]:
#top 10 products by quantity
#المنتجات الأكثر مبيعاً
pd.read_sql_query("""SELECT StockCode,Description,SUM(Quantity) AS total_product_quantity FROM ecommerce GROUP BY StockCode,Description ORDER BY total_product_quantity DESC LIMIT 10""",conn)

  StockCode                         Description  total_product_quantity
0     84077   WORLD WAR 2 GLIDERS ASSTD DESIGNS                   53847
1    85099B             JUMBO BAG RED RETROSPOT                   47363
2     84879       ASSORTED COLOUR BIRD ORNAMENT                   36381
3     22197                      POPCORN HOLDER                   36334
4     21212     PACK OF 72 RETROSPOT CAKE CASES                   36039
5    85123A  WHITE HANGING HEART T-LIGHT HOLDER                   35025
6     23084                  RABBIT NIGHT LIGHT                   30680
7     22492             MINI PAINT SET VINTAGE                    26437
8     22616          PACK OF 12 LONDON TISSUES                    26315
9     21977  PACK OF 60 PINK PAISLEY CAKE CASES                   24753

In [14]:
#Nunber of countries vs products 
pd.read_sql_query("""SELECT COUNT(DISTINCT Country)AS contry_num,COUNT(DISTINCT Description)AS product_num FROM ecommerce""",conn )

   contry_num  product_num
0          38         4223

لدينا 4223 منتج ب 38 دولة

In [82]:
#عدد الأسطر الكلي
#Total number of records 
pd.read_sql_query("""SELECT COUNT(*)AS total_records FROM ecommerce""",conn )

   total_records
0         541909

In [88]:
#عدد الأسطر التي لاتحوي زبون
pd.read_sql_query("""SELECT COUNT(*) AS unknown_cus FROM ecommerce WHERE CustomerID IS NULL""",conn )

   unknown_cus
0       135080

In [89]:
#عدد الأسطر التي لاتحوي فواتير
pd.read_sql_query("""SELECT COUNT(*) AS unknown_cus FROM ecommerce WHERE InvoiceNO IS NULL""",conn )

   unknown_cus
0            0

جميع الأسطر تحوي أرقام فواتير

In [90]:
#عدد الفواتير غير معروفة الموقع 
pd.read_sql_query("""SELECT COUNT(*) AS unknown_cou FROM ecommerce WHERE COuntry IS NULL""",conn )

   unknown_cou
0            0

In [92]:
#what is the countries included
pd.read_sql_query("""SELECT DISTINCT Country AS countries FROM ecommerce ORDER BY Country""",conn )

               countries
0              Australia
1                Austria
2                Bahrain
3                Belgium
4                 Brazil
5                 Canada
6        Channel Islands
7                 Cyprus
8         Czech Republic
9                Denmark
10                  EIRE
11    European Community
12               Finland
13                France
14               Germany
15                Greece
16             Hong Kong
17               Iceland
18                Israel
19                 Italy
20                 Japan
21               Lebanon
22             Lithuania
23                 Malta
24           Netherlands
25                Norway
26                Poland
27              Portugal
28                   RSA
29          Saudi Arabia
30             Singapore
31                 Spain
32                Sweden
33           Switzerland
34                   USA
35  United Arab Emirates
36        United Kingdom
37           Unspecified

In [95]:
#ماهو التوزع الجغرافي للداتا
#first 10 countries
pd.read_sql_query("""SELECT DISTINCT Country AS c FROM ecommerce """,conn )

                       c
0         United Kingdom
1                 France
2              Australia
3            Netherlands
4                Germany
5                 Norway
6                   EIRE
7            Switzerland
8                  Spain
9                 Poland
10              Portugal
11                 Italy
12               Belgium
13             Lithuania
14                 Japan
15               Iceland
16       Channel Islands
17               Denmark
18                Cyprus
19                Sweden
20               Austria
21                Israel
22               Finland
23               Bahrain
24                Greece
25             Hong Kong
26             Singapore
27               Lebanon
28  United Arab Emirates
29          Saudi Arabia
30        Czech Republic
31                Canada
32           Unspecified
33                Brazil
34                   USA
35    European Community
36                 Malta
37                   RSA

In [18]:
#NULL VALUE Analysis: DEscreption column
#ماهو عدد الأعمدة التي لاتحوي منتجات
pd.read_sql_query("""SELECT  COUNT(*) AS no_prod_name FROM ecommerce WHERE Description IS NULL""",conn )

   no_prod_name
0          1454

In [19]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [20]:
#NULL VALUE Analysis: CustomerID    column
pd.read_sql_query("""SELECT  COUNT(*) AS no_prod_name FROM ecommerce WHERE CustomerID   IS NULL""",conn )

   no_prod_name
0        135080

In [21]:
#NULL VALUE Analysis: CustomerID column  count all people whose customerID is available
pd.read_sql_query("""SELECT  COUNT(*) AS unknown_customer_count FROM ecommerce WHERE CustomerID  IS NOT NULL""",conn )

   prod_name
0     406829

In [96]:
pd.read_sql_query("""SELECT  COUNT(DISTINCT CustomerID) AS prod_name FROM ecommerce""",conn )

   prod_name
0       4372

In [97]:
#calc average quantity of JUMBO BAG RED RETROSPOT
pd.read_sql_query("""SELECT  ROUND(AVG(Quantity)) AS gift_avg_quan FROM ecommerce where Description = 'JUMBO BAG RED RETROSPOT'""",conn )

   gift_avg_quan
0           22.0

In [27]:
#calc average quantity of POPCORN HOLDER
pd.read_sql_query("""SELECT  AVG(Quantity) AS h_avg_quan FROM ecommerce where Description = 'POPCORN HOLDER'""",conn )

   h_avg_quan
0   42.004624

In [98]:
#calc average unit price for all products for the e-shop
pd.read_sql_query("""SELECT  ROUND(AVG(UnitPrice)) AS p_avg FROM ecommerce""",conn )

   p_avg
0    5.0

In [29]:
#calc sum of popcorn holder quantity 
pd.read_sql_query("""SELECT  SUM(Quantity) AS popcorn_quantity  FROM ecommerce where Description = 'POPCORN HOLDER'""",conn )

   popcorn_quantity
0             36334

In [30]:
#calc sum of popcorn holder quantity 
pd.read_sql_query("""SELECT  SUM(Quantity) AS bag_quantity  FROM ecommerce where Description = 'JUMBO BAG RED RETROSPOT'""",conn )

   bag_quantity
0         47363

In [31]:
#calc sum of popcorn holder quantity 
pd.read_sql_query("""SELECT  MAX(UnitPrice) FROM ecommerce """,conn )

   MAX(UnitPrice)
0         38970.0

Data SUMMERIZe

In [32]:
#How many incoives in my data ?
pd.read_sql_query("""SELECT  COUNT(InvoiceNo) AS invoice_no  FROM ecommerce """,conn )

   invoice_no
0      541909

In [33]:
#How many products in my data ?
pd.read_sql_query("""SELECT  COUNT(Description) AS product_no  FROM ecommerce """,conn )

   product_no
0      540455

In [99]:
#How many countries are there in my data ?
pd.read_sql_query("""SELECT  COUNT(DISTINCT Country) AS country_no  FROM ecommerce """,conn )

   country_no
0          38

DATA TYPES SUMMERIZE

In [37]:
pd.read_sql_query("""PRAGMA table_info(ecommerce) """,conn )

   cid         name     type  notnull dflt_value  pk
0    0    InvoiceNo     TEXT        0       None   0
1    1    StockCode     TEXT        0       None   0
2    2  Description     TEXT        0       None   0
3    3     Quantity  INTEGER        0       None   0
4    4  InvoiceDate     TEXT        0       None   0
5    5    UnitPrice     REAL        0       None   0
6    6   CustomerID     REAL        0       None   0
7    7      Country     TEXT        0       None   0

In [40]:
df = pd.read_sql_query("SELECT InvoiceDate FROM ecommerce", conn)

df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'], dayfirst=True, errors='coerce')

df['InvoiceDate'].min(), df['InvoiceDate'].max()

(Timestamp('2010-01-12 08:26:00'), Timestamp('2011-12-10 17:19:00'))

In [41]:
pd.read_sql_query("""
SELECT 
    MIN(datetime(InvoiceDate)) AS min_date,
    MAX(datetime(InvoiceDate)) AS max_date
FROM ecommerce
""", conn)

  min_date max_date
0     None     None

datetime invalid solution here

In [42]:
pd.read_sql_query("""
SELECT 
     MIN(strftime('%Y-%m-%d %H:%M', InvoiceDate)) AS min_date,
     MAX(strftime('%Y-%m-%d %H:%M', InvoiceDate)) AS max_date
FROM ecommerce
""", conn)

  min_date max_date
0     None     None

In [43]:
# 1. حول العمود في الباندا (هو سيعرف كيف يعالج 1/1 و 10/12 تلقائياً)
df = pd.read_sql_query("SELECT * FROM ecommerce", conn)
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

# 2. الآن استخرجي الأقدم والأحدث بكل سهولة وبدقة 100%
print(df['InvoiceDate'].min())
print(df['InvoiceDate'].max())

2010-12-01 08:26:00
2011-12-09 12:50:00

In [44]:
# الخطوة 1: سحب البيانات كما هي
query = "SELECT InvoiceDate FROM ecommerce"
df = pd.read_sql_query(query, conn)

# الخطوة 2: التحويل الاحترافي (هذا السطر هو سحر محلل البيانات)
# نستخدم errors='coerce' للتعامل مع أي بيانات خاطئة و dayfirst حسب صيغة ملفك
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'], errors='coerce')

# الخطوة 3: التحقق من "صحة" البيانات بعد التحويل
print(f"عدد القيم التي فشل تحويلها: {df['InvoiceDate'].isna().sum()}")

عدد القيم التي فشل تحويلها: 0

In [45]:
# الخطوة 4: الحصول على النتائج بدقة 100%
oldest = df['InvoiceDate'].min()
latest = df['InvoiceDate'].max()

print(f"الأقدم: {oldest}")
print(f"الأحدث: {latest}")

الأقدم: 2010-12-01 08:26:00
الأحدث: 2011-12-09 12:50:00

aggregation func using where to analyze subset

In [46]:
#what IS the product with hiest total sold quntities in us 
query = """ SELECT description, SUM(quantity)  FROM ecommerce where country = "United Kingdom" """

In [47]:
pd.read_sql_query(query, conn)

                          Description  SUM(quantity)
0  WHITE HANGING HEART T-LIGHT HOLDER        4263829

In [48]:
pd.read_sql_query("""SELECT  Description,SUM(Quantity)  FROM ecommerce WHERE country = "United Kingdom" """,conn )

                          Description  SUM(Quantity)
0  WHITE HANGING HEART T-LIGHT HOLDER        4263829

In [49]:
pd.read_sql_query("""SELECT (3 + 4) """,conn )

   (3 + 4)
0        7

In [50]:
pd.read_sql_query("""SELECT (4 / 3) """,conn )

   (4 / 3)
0        1

In [51]:
pd.read_sql_query("""SELECT (4.0 / 3.0) """,conn )

   (4.0 / 3.0)
0     1.333333

In [52]:
query = "SELECT * FROM ecommerce ORDER BY Country"
df = pd.read_sql_query(query, conn)

In [53]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536389,22941,CHRISTMAS LIGHTS 10 REINDEER,6,12/1/2010 10:03,8.50,12431.0,Australia
1,536389,21622,VINTAGE UNION JACK CUSHION COVER,8,12/1/2010 10:03,4.95,12431.0,Australia
2,536389,21791,VINTAGE HEADS AND TAILS CARD GAME,12,12/1/2010 10:03,1.25,12431.0,Australia
3,536389,35004C,SET OF 3 COLOURED FLYING DUCKS,6,12/1/2010 10:03,5.45,12431.0,Australia
4,536389,35004G,SET OF 3 GOLD FLYING DUCKS,4,12/1/2010 10:03,6.35,12431.0,Australia

In [64]:
query = "SELECT Country, Description,SUM(Quantity) AS quanSv FROM ecommerce GROUP BY Description, Country"
pd.read_sql_query(query, conn)

              Country                     Description  quanSv
0      United Kingdom                            None  -13609
1                EIRE   4 PURPLE FLOCK DINNER CANDLES       6
2      United Kingdom   4 PURPLE FLOCK DINNER CANDLES     138
3                EIRE   50'S CHRISTMAS GIFT BAG LARGE      48
4              France   50'S CHRISTMAS GIFT BAG LARGE      12
...               ...                             ...     ...
20172  United Kingdom     wrongly marked carton 22804    -256
20173  United Kingdom    wrongly marked. 23343 in box   -3100
20174  United Kingdom    wrongly sold (22719) barcode     170
20175  United Kingdom            wrongly sold as sets    -600
20176  United Kingdom               wrongly sold sets    -975

[20177 rows x 3 columns]

In [65]:
query = """SELECT Country, Description, SUM(Quantity) AS quanSv FROM ecommerce GROUP BY Description,Country """
pd.read_sql_query(query, conn)

              Country                     Description  quanSv
0      United Kingdom                            None  -13609
1                EIRE   4 PURPLE FLOCK DINNER CANDLES       6
2      United Kingdom   4 PURPLE FLOCK DINNER CANDLES     138
3                EIRE   50'S CHRISTMAS GIFT BAG LARGE      48
4              France   50'S CHRISTMAS GIFT BAG LARGE      12
...               ...                             ...     ...
20172  United Kingdom     wrongly marked carton 22804    -256
20173  United Kingdom    wrongly marked. 23343 in box   -3100
20174  United Kingdom    wrongly sold (22719) barcode     170
20175  United Kingdom            wrongly sold as sets    -600
20176  United Kingdom               wrongly sold sets    -975

[20177 rows x 3 columns]